export const config = {
  id: "userId",
  username: "User",
  email: "user@user.com",
  password: "user11",
  JWT_SECRET: "user",
  REFRESH_SECRET: "token",
  keys: "other",
  // dbHost: "localhost",
  // dbUser: "root",
  // dbDatabase: "driver_avisation",
  // dbPassword: "",
  smsApiToken: "7vnZIqbAKQXLhqx3kPeoamBzACxv83j1aRZbfnDv",
  // corsOrigin: "http://localhost:3000",
  dbUser: "simplema_cargo",
  dbDatabase: "simplema_cargo",
  dbPassword: "xziVqJip",
  corsOrigin: "https://simplecargo.networkmanager.pl",
};
